# # Dockerfile-celery
# FROM python:3.12-slim

# # -------------------
# # Set environment
# # -------------------
# ENV PYTHONUNBUFFERED=1 \
#     PIP_NO_CACHE_DIR=1 \
#     PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# WORKDIR /app

# # -------------------
# # System dependencies for Playwright browsers
# # -------------------
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     curl \
#     ca-certificates \
#     gnupg \
#     wget \
#  && rm -rf /var/lib/apt/lists/*

# # -------------------
# # Python dependencies
# # -------------------
# COPY requirements.txt /app/
# RUN pip install --upgrade pip
# RUN pip install -r requirements.txt

# # -------------------
# # Install Playwright and browsers
# # -------------------
# RUN pip install playwright
# RUN playwright install --with-deps

# # -------------------
# # Copy app code
# # -------------------
# COPY . /app

# # -------------------
# # Entrypoint
# # -------------------
# CMD ["celery", "-A", "app.core.celery.celery_app", "worker", "--loglevel=info"]
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates gnupg wget \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install playwright
RUN playwright install --with-deps

COPY . /app


EXPOSE 10000

CMD ["python", "healthcheck.py"]