"""init

Revision ID: 9716076540e3
Revises: 
Create Date: 2026-05-16 12:54:57.272424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9716076540e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'COMPANY', 'USER', name='role_enum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'PENDING', 'DELETED', 'LOCKED', name='account_status_enum'), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signup_ip', sa.String(length=45), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('signup_user_agent', sa.Text(), nullable=True),
    sa.Column('last_login_user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index('ix_accounts_email_role', 'accounts', ['email', 'role'], unique=False)
    op.create_index(op.f('ix_accounts_is_verified'), 'accounts', ['is_verified'], unique=False)
    op.create_index(op.f('ix_accounts_reset_token'), 'accounts', ['reset_token'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_verification_token'), 'accounts', ['verification_token'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_profiles_account_id'), 'admin_profiles', ['account_id'], unique=True)
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_logo_url', sa.String(length=1024), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('billing_plan', sa.String(length=100), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_account_id'), 'company_profiles', ['account_id'], unique=True)
    op.create_table('uptime_monitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uptime_monitors_account_id'), 'uptime_monitors', ['account_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_account_id'), 'user_profiles', ['account_id'], unique=True)
    op.create_table('uptime_pings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitor_id', sa.UUID(), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['uptime_monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uptime_pings_checked_at'), 'uptime_pings', ['checked_at'], unique=False)
    op.create_index(op.f('ix_uptime_pings_monitor_id'), 'uptime_pings', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uptime_pings_monitor_id'), table_name='uptime_pings')
    op.drop_index(op.f('ix_uptime_pings_checked_at'), table_name='uptime_pings')
    op.drop_table('uptime_pings')
    op.drop_index(op.f('ix_user_profiles_account_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_uptime_monitors_account_id'), table_name='uptime_monitors')
    op.drop_table('uptime_monitors')
    op.drop_index(op.f('ix_company_profiles_account_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_admin_profiles_account_id'), table_name='admin_profiles')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_accounts_verification_token'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_reset_token'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_verified'), table_name='accounts')
    op.drop_index('ix_accounts_email_role', table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
