"""add admin and company profiles

Revision ID: af41e08617ff
Revises: 47ec4f33a26f
Create Date: 2025-12-11 15:19:22.083138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af41e08617ff"
down_revision: Union[str, Sequence[str], None] = "47ec4f33a26f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("is_super_admin", sa.Boolean(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_profiles_account_id"),
        "admin_profiles",
        ["account_id"],
        unique=True,
    )
    op.create_table(
        "company_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("company_logo_url", sa.String(length=1024), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("billing_plan", sa.String(length=100), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_profiles_account_id"),
        "company_profiles",
        ["account_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_profiles_account_id"), table_name="company_profiles")
    op.drop_table("company_profiles")
    op.drop_index(op.f("ix_admin_profiles_account_id"), table_name="admin_profiles")
    op.drop_table("admin_profiles")
    # ### end Alembic commands ###
